name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:
    types:
      - checks_requested
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: self-hosted
