name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
